public class Receipt {

    public String first() {

        return " <!DOCTYPE html>\n"
            + "<html lang=\"ko\">\n"
            + "\n"
            + "<head>\n"
            + "  <meta charset=\"UTF-8\">\n"
            + "  <style>\n"
            + "    .end {\n"
            + "      text-align: end;\n"
            + "    }\n"
            + " body { background : white; }"
            + "  </style>\n"
            + "</head>\n"
            + "\n"
            + "<body>\n"
            + "  <table style=\"border: solid 1px; width : 280px;\">\n"
            + "    <thead>\n"
            + "      <tr>\n"
            + "        <td colspan=\"4\">\n"
            + "          <br><b>총 결제금액</b>\n"
            + "          <br>\n"
            + "          <h3>52,800 원</h3>\n"
            + "          <hr>\n"
            + "        </td>\n"
            + "      </tr>\n"
            + "    </thead>\n"
            + "    <tbody style=\"font-size : 12px;\">\n"
            + "      <tr>\n"
            + "        <td colspan=3><b>gdgd</b></td>\n"
            + "        <td class=\"end\"><b>39,900원</b></td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3><b>회원복</b></td>\n"
            + "        <td class=\"end\"><b>3,000원</b></td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3><b>락커</b></td>\n"
            + "        <td class=\"end\"><b>9,990 원</b></td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=4>-------------------------------------------------------</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>승인 번호</td>\n"
            + "        <td class=\"end\">30023742</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>카드 종류</td>\n"
            + "        <td class=\"end\">국민KB카드</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>결제일자</td>\n"
            + "        <td class=\"end\">2023-03-28 00:31</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>승인번호</td>\n"
            + "        <td class=\"end\">30023742</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>할부기간</td>\n"
            + "        <td class=\"end\">일시불</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=4>-------------------------------------------------------</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>구매 상점</td>\n"
            + "        <td class=\"end\">gdg</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>대표자</td>\n"
            + "        <td class=\"end\">브루노 마스</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>사업자</td>\n"
            + "        <td class=\"end\">606-60-60060</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>구매지점</td>\n"
            + "        <td class=\"end\">30023742</td>\n"
            + "      </tr>\n"
            + "      <tr>\n"
            + "        <td colspan=3>주소</td>\n"
            + "        <td class=\"end\">부산광역시 부산진구 부전동 165-2 B1</td>\n"
            + "      </tr>\n"
            + "      <td colspan=4>-------------------------------------------------------</td>\n"
            + "      </tr>\n"
            + "    </tbody>\n"
            + "  </table>\n"
            + "</body>\n"
            + "\n"
            + "</html>";
    }

}
